services:
  manager:
    image: monitoring-manager:latest
    ports:
      - "8889:8889" # Prometheus exporter
    depends_on:
      - mosquitto

  agent:
    image: monitoring-agent:latest
    depends_on:
      - mosquitto
    ports:
      - "8080:8888"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090" # Prometheus web UI

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
