services:
  monitoring-manager:
    image: monitoring-manager:latest
    container_name: monitoring-manager
    hostname: monitoring-manager
    restart: unless-stopped
    volumes:
      - /home/ubuntu/benchmarks/monitoring:/bench
      - ./monitoring-manager/config/opentelemetry-collector/opentelemetry-config.yaml:/otel/opentelemetry-config.yaml
    ports:
      # gRPC port for the Oakestra processor
      - "${MONITORING_MANAGER_GRPC_PORT}:${MONITORING_MANAGER_GRPC_PORT}"
      # HTTP server port for the heuristic engine
      - "${MONITORING_MANAGER_HTTP_PORT}:${MONITORING_MANAGER_HTTP_PORT}"
      - "1777:1777"
    environment:
      # Add any environment variables if needed
      - DEBUG=false
      - HTTP_PORT=${MONITORING_MANAGER_HTTP_PORT}
      - GRPC_PORT=${MONITORING_MANAGER_GRPC_PORT}
      - MQTT_BROKER_HOST=${MQTT_BROKER_URL}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - MONGODB_HOST=${MONGODB_NET_URL}
      - MONGODB_PORT=${MONGODB_NET_PORT}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - SERVICE_MANAGER_HOST=${SERVICE_MANAGER_URL}
      - SERVICE_MANAGER_PORT=${SERVICE_MANAGER_PORT}
