receivers:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver
  hostmetrics:
    collection_interval: 5s
    root_path: /
    scrapers:
      cpu:
      memory:
      load:
        cpu_average: true
      network:
      paging:
      #processes:
      #process:

  hostmetrics/disk:
    collection_interval: 60s
    root_path: /
    scrapers:
      disk:
      filesystem:

exporters:
  # metrics are for now forwarded to prometheus by the monitoring-manager
  otlp:
    endpoint: monitoring-manager:4317 # TODO: configure endpoint here
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, hostmetrics/disk]
      exporters: [debug, otlp] # can also use otlpgrpc here
