dist:
  # module: github.com/smnzlnsk/monitoring-manager
  description: Master Thesis - Telemetry driven Network Optimisation in Edge-Cloud Orchestration Frameworks
  otelcol_version: 0.109.0
  version: 0.0.1
  output_path: /tmp/monitoring-manager
  name: monitoringmanager

receivers:
  - gomod: github.com/smnzlnsk/opentelemetry-components/receiver/mqttreceiver v0.0.0
    path: receivers/mqttreceiver

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.109.0
  - gomod: github.com/smnzlnsk/opentelemetry-components/processor/oakestraprocessor v0.0.0
    path: processors/oakestraprocessor
  - gomod: github.com/smnzlnsk/opentelemetry-components/processor/oakestraheuristicengine v0.0.0
    path: processors/oakestraheuristicengine

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.109.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.109.0
  - gomod: github.com/smnzlnsk/opentelemetry-components/exporter/httpexporter v0.0.0
    path: exporters/httpexporter
extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.109.0
