dist:
  # module: github.com/smnzlnsk/monitoring-manager
  description: Master Thesis - Telemetry driven Network Optimisation in Edge-Cloud Orchestration Frameworks
  otelcol_version: 0.109.0
  version: 0.0.1
  output_path: build
  name: manager

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.109.0
  - gomod: github.com/smnzlnsk/opentelemetry-components/receiver/mqttreceiver v0.0.1

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.109.0
  #  - gomod: github.com/smnzlnsk/opentelemetry-components/processor/oakestraprocessor v0.0.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.109.0
  - gomod: github.com/smnzlnsk/opentelemetry-components/exporter/mqttexporter v0.0.1
