dist:
  module: github.com/smnzlnsk/monitoring-manager
  description: Master Thesis - Telemetry driven Network Optimisation in Edge-Cloud Orchestration Frameworks
  otelcol_version: 0.105.0
  version: 0.0.1
  go: /opt/homebrew/bin/go

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.105.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.105.0
