dist:
  # module: github.com/smnzlnsk/monitoring-manager
  description: Master Thesis - Telemetry driven Network Optimisation in Edge-Cloud Orchestration Frameworks
  otelcol_version: 0.108.1
  version: 0.0.1
  output_path: build
  name: manager

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.108.1
  - gomod: github.com/smnzlnsk/mqttreceiver v0.0.1
    path: ./internal/mqttreceiver

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.108.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.108.0
