dist:
  module: github.com/smnzlnsk/monitoring-manager/agent
  name: oakestra-monitoring-agent
  description: Master Thesis - Telemetry driven Network Optimisation in Edge-Cloud Orchestration Frameworks
  otelcol_version: 0.105.0
  output_path: ./bin/oakestra-monitoring-agent
  version: 0.0.1
  go: /opt/homebrew/bin/go

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.105.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.105.0
  #- gomod: go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.28.0
  #- gomod: go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.28.0
