receivers:
  mqtt:
    interval: 1s
    client_id: manager_receiver_mac
    broker:
      host: &brokerhost localhost
      port: &brokerport 1883

exporters:
  debug:
    verbosity: basic
  prometheus:
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: false
    #resource_to_telemetry_conversion:
    #  enabled: true
  mqtt:
    interval: 1s
    client_id: manager_exporter_mac
    topic: metrics/done
    broker:
      host: *brokerhost
      port: *brokerport

processors:
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["machine"], resource.attributes["machine"])

service:
  telemetry:
    metrics:
      level:
  pipelines:
    metrics:
      receivers: [mqtt]
      processors: [transform]
      exporters: [mqtt]
