receivers:
  mqttreceiver:
    interval: 1s
    broker:
      host: mosquitto
      port: 1883

exporters:
  debug:
    verbosity: basic
  prometheus:
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: true
    #resource_to_telemetry_conversion:
    #  enabled: true
  backend:

processors:
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["machine"], resource.attributes["machine"])

service:
  telemetry:
    metrics:
      level:
  pipelines:
    metrics:
      receivers: [mqttreceiver]
      processors: [transform]
      exporters: [backend, debug, prometheus]
