receivers:
  mqtt:
    interval: 1s
    client_id: monitoring-manager
    broker:
      host: 127.0.0.1
      port: 1883

exporters:
  
  debug:
    verbosity: normal

  http:
    endpoint:
      # TODO: set to address of routing-manager
      ip: 127.0.0.1
      port: 1880

processors:
  oakestra:
    subprocessors:
      cpu:

  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["machine"], resource.attributes["machine"])

service:
  telemetry:
    metrics:
      level:
  pipelines:
    metrics:
      receivers: [mqtt]
      processors: [oakestra]
      exporters: [http] #[http, debug]
