receivers:
  mqtt:
    interval: 1s
    client_id: monitoring-manager
    broker:
      host: ${MQTT_BROKER_HOST}
      port: ${MQTT_BROKER_PORT}

exporters:
  
  debug:
    verbosity: basic

processors:
  groupbyattrs:

  heuristicengine:
    http_server:
      enabled: true
      host: 0.0.0.0
      port: ${HTTP_PORT}
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
    service_manager:
      host: ${SERVICE_MANAGER_HOST}
      port: ${SERVICE_MANAGER_PORT}
  
  oakestra:
    subprocessors:
      cpu:
      memory:
      application:
    grpc_port: ${GRPC_PORT}
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["machine"], resource.attributes["machine"])

extensions:
  pprof:
    endpoint: 0.0.0.0:1777

service:
  extensions: [pprof]
  telemetry:
    metrics:
      level:
  pipelines:
    metrics:
      receivers: [mqtt]
      processors: [oakestra, heuristicengine, groupbyattrs]
      exporters: [debug] #[http, debug]
