receivers:
  mqtt:
    interval: 1s
    client_id: monitoring-manager
    broker:
      host: 131.159.24.1
      port: 10003

exporters:
  
  debug:
    verbosity: normal

processors:
  groupbyattrs:

  heuristicengine:
    http_server:
      enabled: true
      host: 0.0.0.0
      port: 8081
    persistent_metrics: false
    mongodb:
      host: 131.159.24.1
      port: 10108
      username: 
      password: 
    service_manager:
      host: 131.159.24.1
      port: 10110

  oakestra:
    subprocessors:
      cpu:
      memory:
      application:
    grpc_port: 5568
    mongodb:
      host: 131.159.24.1
      port: 10108
      username: 
      password: 
    
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["machine"], resource.attributes["machine"])

extensions:
  pprof:
    endpoint: 0.0.0.0:1777

service:
  extensions: [pprof]
  telemetry:
    metrics:
      level:
  pipelines:
    metrics:
      receivers: [mqtt]
      processors: [groupbyattrs, oakestra, heuristicengine]
      exporters: [debug] #[http, debug]
