receivers:
  mqtt:
    interval: 1s
    client_id: monitoring-manager
    broker:
      host: 131.159.24.1
      port: 10003

exporters:
  
  debug:
    verbosity: detailed

processors:
  groupbyattrs:

  heuristicengine:
    http_server:
      enabled: true
      host: 0.0.0.0
      port: 8081
    mongodb:
      host: 131.159.24.1
      port: 10108
      username: 
      password: 
  
  oakestra:
    subprocessors:
      cpu:
      memory:
      application:
    grpc_port: 5568
    mongodb:
      host: 131.159.24.1
      port: 10108
      username: 
      password: 
    
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["machine"], resource.attributes["machine"])

service:
  telemetry:
    metrics:
      level:
  pipelines:
    metrics:
      receivers: [mqtt]
      processors: [oakestra, heuristicengine, groupbyattrs]
      exporters: [debug] #[http, debug]
